/* history-list.vapi generated by valac, do not modify. */

[CCode (cprefix = "HistoryList", lower_case_cprefix = "history_list_")]
namespace HistoryList {
}
[CCode (cheader_filename = "history-list.h")]
public static Midori.Extension extension_init ();
