#!/bin/bash

Input="$@"

mkdir -p ./$Input

cd ./scalable

for i in $(ls ./); do

mkdir ../$Input/$i

done

for i in $(ls ./emotes); do

convert "./emotes/$i" -scale $Input'!' "$HOME/Simple-Fork/$Input/emotes/$i"

done

for i in $(ls ./mimetypes); do

convert "./mimetypes/$i" -scale $Input'!' "$HOME/Simple-Fork/$Input/mimetypes/$i"

done

for i in $(ls ./stock); do

convert "./stock/$i" -scale $Input'!' "$HOME/Simple-Fork/$Input/stock/$i"

done

for i in $(ls ./actions); do

convert "./actions/$i" -scale $Input'!' "$HOME/Simple-Fork/$Input/actions/$i"

done

for i in $(ls ./emblems); do

convert "./emblems/$i" -scale $Input'!' "$HOME/Simple-Fork/$Input/emblems/$i"

done

for i in $(ls ./places); do

convert "./places/$i" -scale $Input'!' "$HOME/Simple-Fork/$Input/places/$i"

done

for i in $(ls ./categories); do

convert "./categories/$i" -scale $Input'!' "$HOME/Simple-Fork/$Input/categories/$i"

done

for i in $(ls ./status); do

convert "./status/$i" -scale $Input'!' "$HOME/Simple-Fork/$Input/status/$i"

done

for i in $(ls ./apps); do

convert "./apps/$i" -scale $Input'!' "$HOME/Simple-Fork/$Input/apps/$i"

done

for i in $(ls ./devices); do

convert "./devices/$i" -scale $Input'!' "$HOME/Simple-Fork/$Input/devices/$i"

done



exit