#!/bin/bash
# Licensed under the GNU General Public License Version 2
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
####################################################################################################
## Authored by Anthony Nordquist of the SalineOS project. http://www.salineos.com/  salinelinux@gmail.com 
## Copyright 2011,2012 Anthony Nordquist 

Icon="--window-icon=image-x-generic"

ConvertArray=("jpg" "gif" "jpeg" "png" "tiff" "dpx" "xhtml" "bmp" "pdf")

ConvertTo=$(yad $Icon --height=285 --width=300 --no-headers --list --column="Select One" --title="Image(s) Conversion" --text="Select the format to convert to" "${ConvertArray[@]}")

ret="$?"

ConvertTo=$(echo "$ConvertTo" | awk -F '|' '{print $1}')

if [ "$ret" = "1" ]; then
 exit
elif [ "$ret" = "252" ]; then
 exit
elif [ "$ConvertTo" = "" ]; then
 yad $Icon --title=ERROR --text="          No image format selected          \n" --button=$"gtk-quit:1"
 exit 0
fi

progressbar () {
tail -f /usr/bin/convert-image-ca |  yad $Icon --no-buttons --progress --pulsate --auto-close --title="Image(s) Conversion" --text="$@"
}

progressbar "     Converting image(s) to $ConvertTo now     \n" &

for i in "$@"; do
 Extension="$(echo "$i" | awk -F "." '{print $NF}')"
 Converted="$(echo "$i" | sed -e "s|.$Extension||g")"
 convert "$i" "$Converted.$ConvertTo"
done

sleep 5

killall -KILL tail

yad $Icon --title="Image(s) Conversion" --text="            Conversion Complete            \n" --button=$"gtk-ok:1"

exit
