#!/bin/bash
# Licensed under the GNU General Public License Version 2
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
#################################################################################################### 
# Authored Anthony Nordquist of the SalineOS project http://www.salineos.com salinelinux@gmail.com
# Copyright 2011 Under the GNU GPL2 License. 

Selection=$(zenity --list --column="Select One" --title="Scale Image(s)" --text="Select the size to scale image to." ext3 ext4 fat32)
