#!/bin/bash

mkdir -p $HOME/.notes-ca

Input="$@"


if [ -f "$HOME/.notes-ca/$Input" ]; then
 Text="$(cat "$HOME/.notes-ca/$Input")"
fi

Note="$(echo "$Text" | yad --text-info --editable --title="$Input Notes" --height=550 --width=450 --button=$"gtk-quit:3" --button=$"gtk-save:2" )"

ret="$?"

if [ "$ret" = "3" ]; then
 exit 0
fi

echo "$Note"

rm "$HOME/.notes-ca/$Input"

if [ ! -f "$HOME/.notes-ca/$Input" ]; then
 touch "$HOME/.notes-ca/$Input"
fi

echo "$Note">>"$HOME/.notes-ca/$Input"

exit
