#!/bin/bash
# Licensed under the GNU General Public License Version 2
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
####################################################################################################
## Authored and maintained by Anthony Nordquist of the SalineOS project. http://www.salineos.com/  salinelinux@gmail.com 
## Copyright Anthony Nordquist 2012

Input="$@"

Icon="--window-icon=folder-copy"

Destination=$(yad $Icon --file-selection --height="450" --directory --text="                                   Please select the folder to copy to                                   \n" --title="Sync Folder" --button=$"gtk-quit:3" --button=$"gtk-ok:2")

echo "$Destination"

ret="$?"

if [ "$ret" = "3" ]; then
 exit
elif [ "$ret" = "252" ];then
 exit
elif [ "$Destination" = "" ]; then
 yad --title="ERROR" --text="     No destination folder was selected.     \n" --button=$"gtk-quit:1"
 exit
fi

## Add the option to delete files that don't exist in $Input
yad --title="Sync Folder" $Icon --width=250 --wrap --text="Would you like to delete files that don't exist in $Input from $Destination?\n" --button=$"gtk-no:3" --button=$"gtk-yes:5"

ret="$?"

if [ "$ret" = "252" ]; then
 yad $Icon --title="Sync Folder" --text="          Operation cancelled          \n" --button=$"gtk-quit:1"
 exit
elif [ "$ret" = "3" ]; then
 Delete="No"
elif [ "$ret" = "5" ]; then
 Delete="Yes"
fi

## I think we should warn the user what this will actually do :)
yad --title="Sync Folder" $Icon --width=250 --wrap --text="This operation will sync the contents of $Input to $Destination, would you like to continue?\n" --button=$"gtk-no:3" --button=$"gtk-yes:5"

ret="$?"

if [ "$ret" = "252" ]; then
 yad $Icon --title="Sync Folder" --text="          Operation cancelled          \n" --button=$"gtk-quit:1"
 exit
elif [ "$ret" = "3" ]; then
 yad $Icon --title="Sync Folder" --text="          Operation cancelled          \n" --button=$"gtk-quit:1"
 exit
fi

progressbar () {
tail -f /usr/bin/convert-image-ca |  yad $Icon --no-buttons --progress --pulsate --auto-close --title="Sync Folder" --text="$@"
}



## Actually run the rsync 
if [ "$Delete" = "Yes" ]; then
 progressbar "       Syncing $Input to $Destination      \n" &
 rsync --delete -a -u -H "$Input/" "$Destination"
 sleep 5
 killall -KILL tail
else
 progressbar "       Syncing $Input to $Destination      \n" &
 rsync -a -u -H "$Input/" "$Destination"
 sleep 5
 killall -KILL tail
fi
exit

