#!/bin/bash
# Licensed under the GNU General Public License Version 2
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
####################################################################################################
# Copyright 2012 Anthony Nordquist http://www.salineos.com salinelinux@gmail.com 


FlashCookieSize=$(du -chs --apparent-size $HOME/.adobe $HOME/.macromedia/Flash_Player | grep 'total' | awk -F ' ' '{print $1}')

PackageCacheSize=$(du -chs --apparent-size /var/cache/apt/archives | grep 'total' | awk -F ' ' '{print $1}')

LogsSize=$(du -chs --apparent-size $HOME/.xsession-errors | grep 'total' | awk -F ' ' '{print $1}')

ThumbnailsSize=$(du -chs --apparent-size $HOME/.thumbnails | grep 'total' | awk -F ' ' '{print $1}')

Operation=$(yad --button=$"Exit:3" --button=$"gtk-ok:2" --list --text="Please select the actions you wish to perform" --height="250" --checklist --multiple --on-top --column=' ' --column="Action" --column="Size" --title="Clean" --print-column="2" X Flash-Cookies "$FlashCookieSize" X Logs "$LogsSize" X Package-Cache "$PackageCacheSize" X Un-Needed-Packages 'N/A' X Thumbnails "$ThumbnailsSize")

ret=$?

echo "$Operation"


if [ "$ret" = "252" ]; then
 exit 0
elif [ "$ret" = "3" ]; then
 exit 0 
fi


if [ "$(echo "$Operation" | grep "Flash-Cookies")" != "" ]; then
 rm -rf $HOME/.adobe
 rm -rf $HOME/.macromedia/Flash_Player
 mkdir -p $HOME/.adobe
 mkdir -p $HOME/.macromedia/Flash_Player
elif [ "$(echo "$Operation" | grep "Package-Cache")" != "" ]; then
 apt-get clean
elif [ "$(echo "$Operation" | grep "Logs")" != "" ]; then
 rm $HOME/.xsession-errors
 touch $HOME/.xsession-errors
elif [ "$(echo "$Operation" | grep "Thumbnails")" != "" ]; then
 rm -rf $HOME/.thumbnails
 mkdir -p $HOME/.thumbnails
elif [ "$(echo "$Operation" | grep "Packages")" != "" ]; then
 DialogText="$(apt-get -s autoremove | grep '  ')"
 yad --on-top --wrap --center --title="Clean" --image=gtk-dialog-question --text="The following packages will be removed:\n\n$DialogText" --button=$"gtk-no:1" --button=$"gtk-yes:0"
 if [ "$?" = "0" ]; then
  apt-get -y autoremove
 fi
fi
exit 
