#!/bin/bash
aptitude update
apt-get -y remove task-xfce-desktop xfce4-goodies
aptitude keep-all

aptitude -y dist-upgrade

aptitude -y purge lightdm

aptitude install -y system-config-printer libsdl-mixer1.2 \
libsdl-1.2debian-alsa exaile xfburn parole osmo icedove\
 pidgin pidgin-microblog pidgin-themes pidgin-privacy-please\
 pidgin-facebookchat pidgin-plugin-pack galculator xfce4-dict \
catfish ristretto gimp gimp-plugin-registry evince libreoffice \
libreoffice-help-en-us libreoffice-gtk ure uno-libs3 unoconv \
libreoffice-calc libreoffice-draw libreoffice-impress libreoffice-math \
myspell-en-us deluge libopenal1 xserver-xorg-input-joystick cheese \
pm-utils kvm imagemagick nrg2iso dmg2img ccd2iso mdf2iso libsdl-mixer1.2 \
icedtea-7-plugin openjdk-7-jre openjdk-7-jre-headless libsane-extras \
xsane hplip cups-pdf hplip-cups bluez-cups httping curl ntp xfce4-volumed \
thunar-volman gtkhash fuseiso apt-file yet-another-dialog midori \
midori-web-application-plugin sos-firewall grub-doctor salineos-system-utilities \
salineos-backup salineos-custom-actions localizesys salineos-installer \
packagekit-url clean simple-fork-icon-theme salty-ice-gtk-theme procurator \
saline-get magix-driver-installer slim salineos-autostart xserver-xorg-input-acecad \
xserver-xorg-input-aiptek xserver-xorg-input-elographics \
xserver-xorg-input-joystick xserver-xorg-input-evdev \
xserver-xorg-input-kbd xserver-xorg-input-mouse xserver-xorg-input-mtrack \
xserver-xorg-input-multitouch printer-drivers-all xserver-xorg-input-mutouch \
xserver-xorg-input-penmount xserver-xorg-input-tslib xserver-xorg-input-wacom \
xserver-xorg-video-apm xserver-xorg-ark xserver-xorg-video-ati \
xserver-xorg-video-chips xserver-xorg-video-cirrus xserver-xorg-video-fbdev \
xserver-xorg-video-geode xserver-xorg-video-glamo xserver-xorg-video-glide \
xserver-xorg-video-glint xserver-xorg-video-i128 xserver-xorg-video-i740 \
xserver-xorg-video-intel xserver-xorg-video-ivtv xserver-xorg-video-mach64 \
xserver-xorg-video-mga xserver-xorg-video-neomagic xserver-xorg-video-nouveau \
xserver-xorg-video-openchrome xserver-xorg-video-qxl xserver-xorg-video-r128 \
xserver-xorg-video-radeon xserver-xorg-video-rendition xserver-xorg-video s3 \
xserver-xorg-video-s3virge xserver-xorg-video-savage xserver-xorg-video-siliconmotion \
xserver-xorg-video-sis xserver-xorg-video-sisusb xserver-xorg-video-tdfx \
xserver-xorg-video-tga xserver-xorg-video-trident xserver-xorg-video-tseng \
xserver-xorg-video-vmware xserver-xorg-video-voodoo xserver-xorg-input-synaptics \
xserver-xorg-video-modesetting libnotify-bin file-roller

CurrentKernel=$(uname -r)

if [ $(echo "$CurrentKernel" | grep "pae")" != "" ]; then
 aptitude install -y linux-headers-686-pae
else
 aptitude install -y linux-headers-amd64
fi

apt-get -y --no-install-recommends install gnome-packagekit

aptitude -y purge kexec-tools apt-listchanges brasero exfalso gedit baobab telnet nautilus ssh \
yelp squeeze vlc transmission gigolo xscreensaver gnome-utils-common epdfview \

