#!/bin/bash
# Licensed under the GNU General Public License Version 2
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
####################################################################################################
## Authored by Anthony Nordquist of the SalineOS project. http://www.salineos.com/  salinelinux@gmail.com 
## Copyright 2011 Anthony Nordquist under the GPL V2 License

Rotation=$(zenity --list --column="Select One" --title="Rotate Image(s)" --text="Select the desired number\n of degrees to rotate." 90 180 270)

if [ "$?" = "1" ]; then
 exit
fi

progressbar () {
tail -f /usr/bin/rotate-image-ca |  zenity --progress --pulsate --auto-close --title="Rotate Image(s)" --text="$@"
}

progressbar "Rotating image(s) $Rotation degrees now, please wait..." &

for i in "$@"; do
 convert "$i" -rotate $Rotation "$i"
done

sleep 5

killall -KILL tail

zenity --info --title="Rotate Image(s)" --text="Rotation completed."

exit
