#!/bin/bash
# Licensed under the GNU General Public License Version 2
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
####################################################################################################
## Authored by Anthony Nordquist of the SalineOS project. http://www.salineos.com/  salinelinux@gmail.com 
## Copyright 2011 Anthony Nordquist under the GPL V2 License


Selection=$(zenity --list --column="Select One" --title="Scale Image(s)" --text="Select the size to scale image to." custom 220x176 240x340 320x200 320x240 320x480 352x288 480x320 480x800 480x854 640x350 640x480 640x960 720x400 800x600 1024x768 1152x864 1280x800 1280x1024 1366x768 1400x1050 1440x900 1600x900 1600x1050 1600x1200 1680x1050 1920x1080 1920x1200)

if [ "$?" = "1" ]; then
 exit
fi

progressbar () {
tail -f /usr/bin/scale-image-ca |  zenity --progress --pulsate --auto-close --title="Scale Image(s)" --text="$@"
}

if [ "$Selection" = "custom" ]; then
 ScaleTo="$(zenity --entry --title="Scale Image(s)" --text="Please enter the desired resolution to scale to.")"
if [ "$?" = "1" ]; then
 exit
fi
else
 ScaleTo=$Selection
fi


progressbar "Scaling image(s) to $ScaleTo now, please wait..." &

for i in "$@"; do
 Extension="$(echo "$i" | awk -F "." '{print $NF}')"
 Scaled="$(echo "$i" | sed -e "s|.$Extension||g")"
 convert "$i" -scale $ScaleTo'!' "$Scaled"$ScaleTo."$Extension"
done

sleep 5

killall -KILL tail

zenity --info --title="Scale Image(s)" --text="Scaling operation completed."

exit
