# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1369110351);
user_pref("app.update.lastUpdateTime.background-update-timer", 1369161592);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1369110471);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1369179351);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1369161471);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.download.panel.firstSessionCompleted", true);
user_pref("browser.download.panel.shown", true);
user_pref("browser.migration.version", 9);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.preferences.advanced.selectedTabIndex", 1);
user_pref("browser.rights.3.shown", true);
user_pref("browser.search.selectedEngine", "DuckDuckGo");
user_pref("browser.search.useDBForOrder", true);
user_pref("browser.slowStartup.averageTime", 0);
user_pref("browser.slowStartup.samples", 0);
user_pref("browser.startup.homepage_override.buildID", "20130511120803");
user_pref("browser.startup.homepage_override.mstone", "21.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":0,\"bookmarks\":0}");
user_pref("browser.tabs.warnOnClose", false);
user_pref("datareporting.healthreport.lastDataSubmissionRequestedTime", "1369120392143");
user_pref("datareporting.healthreport.lastDataSubmissionSuccessfulTime", "1369120393440");
user_pref("datareporting.healthreport.lastPingTime", "1369120393440");
user_pref("datareporting.healthreport.lastSubmitID", "2cf19d55-c6c7-47af-8d8c-dd2aadc40007");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1369206793440");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAccepted", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 1);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1368850973566");
user_pref("datareporting.policy.dataSubmissionPolicyResponseTime", "1368852853011");
user_pref("datareporting.policy.dataSubmissionPolicyResponseType", "accepted-info-bar-dismissed");
user_pref("datareporting.policy.firstRunTime", "1368744160226");
user_pref("datareporting.sessions.current.activeTicks", 59);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 1447);
user_pref("datareporting.sessions.current.main", 12);
user_pref("datareporting.sessions.current.sessionRestored", 1357);
user_pref("datareporting.sessions.current.startTime", "1369173531222");
user_pref("datareporting.sessions.current.totalTime", 6438);
user_pref("datareporting.sessions.currentIndex", 28);
user_pref("datareporting.sessions.previous.26", "{\"s\":1369067665070,\"a\":682,\"t\":58724,\"c\":true,\"m\":399,\"fp\":2975,\"sr\":3231}");
user_pref("datareporting.sessions.previous.27", "{\"s\":1369161229857,\"a\":47,\"t\":12282,\"c\":true,\"m\":405,\"fp\":3030,\"sr\":3312}");
user_pref("datareporting.sessions.prunedIndex", 25);
user_pref("dom.mozApps.used", true);
user_pref("dom.w3c_touch_events.expose", false);
user_pref("extensions.adblockedge.currentVersion", "2.0.3");
user_pref("extensions.blocklist.pingCountTotal", 6);
user_pref("extensions.blocklist.pingCountVersion", 3);
user_pref("extensions.bootstrappedAddons", "{\"{fe272bd1-5f76-4ea4-8501-a05d35d823fc}\":{\"version\":\"2.0.3\",\"type\":\"extension\",\"descriptor\":\"/home/user/.mozilla/firefox/sk25m38t.default/extensions/{fe272bd1-5f76-4ea4-8501-a05d35d823fc}.xpi\"}}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:21.0");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/home/user/.firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1368306682000,\"rdfTime\":1368306200000}}},{\"name\":\"app-profile\",\"addons\":{\"{fe272bd1-5f76-4ea4-8501-a05d35d823fc}\":{\"descriptor\":\"/home/user/.mozilla/firefox/sk25m38t.default/extensions/{fe272bd1-5f76-4ea4-8501-a05d35d823fc}.xpi\",\"mtime\":1368745485000}}}]");
user_pref("extensions.lastAppVersion", "21.0");
user_pref("extensions.lastPlatformVersion", "21.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://search/adblock");
user_pref("extensions.ui.locale.hidden", true);
user_pref("gecko.buildID", "20130511120803");
user_pref("gecko.mstone", "21.0");
user_pref("idle.lastDailyNotification", 1369107244);
user_pref("intl.charsetmenu.browser.cache", "windows-1252, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.database", "{\"files\":[{\"fingerprint\":\"e9fb4fe687d7fff189eee11e03a17f4\",\"exists\":true,\"page\":1,\"zoom\":\"auto\",\"scrollLeft\":0,\"scrollTop\":849}]}");
user_pref("pdfjs.migrationVersion", 1);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1369120392);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf,video/3gpp,audio/amr,video/x-ms-asf,video/x-msvideo,video/x-flv,video/x-matroska,audio/mpeg,audio/x-mpegurl,video/mp4,video/mpeg,application/ogg,video/ogg,audio/x-realaudio,audio/x-wav,video/webm,audio/x-ms-wma,video/x-ms-wmv,video/x-ms-wvx,application/xspf+xml");
user_pref("pref.downloads.disable_button.edit_actions", false);
user_pref("privacy.cpd.offlineApps", true);
user_pref("privacy.cpd.siteSettings", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("privacy.sanitize.timeSpan", 0);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1368755910);
user_pref("toolkit.startup.last_success", 1369173531);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1371765832);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
user_pref("xpinstall.whitelist.add.36", "");
