# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1368744520);
user_pref("app.update.lastUpdateTime.background-update-timer", 1368744400);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1368744640);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1368748614);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1368744280);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.download.panel.firstSessionCompleted", true);
user_pref("browser.migration.version", 9);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.rights.3.shown", true);
user_pref("browser.search.selectedEngine", "DuckDuckGo");
user_pref("browser.search.useDBForOrder", true);
user_pref("browser.slowStartup.averageTime", 1109);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage_override.buildID", "20130511120803");
user_pref("browser.startup.homepage_override.mstone", "21.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":2}");
user_pref("browser.tabs.warnOnClose", false);
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1368830560226");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.firstRunTime", "1368744160226");
user_pref("datareporting.sessions.current.activeTicks", 44);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 1069);
user_pref("datareporting.sessions.current.main", 8);
user_pref("datareporting.sessions.current.sessionRestored", 1095);
user_pref("datareporting.sessions.current.startTime", "1368748494273");
user_pref("datareporting.sessions.current.totalTime", 261);
user_pref("datareporting.sessions.currentIndex", 10);
user_pref("datareporting.sessions.previous.0", "{\"s\":1368744159475,\"a\":150,\"t\":1861,\"c\":true,\"m\":12,\"fp\":1954,\"sr\":2931}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1368746220654,\"a\":4,\"t\":74019,\"c\":true,\"m\":13,\"fp\":593,\"sr\":3559}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1368746309465,\"a\":4,\"t\":49,\"c\":true,\"m\":9,\"fp\":505,\"sr\":3195}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1368746363702,\"a\":5,\"t\":167,\"c\":true,\"m\":15,\"fp\":1148,\"sr\":1171}");
user_pref("datareporting.sessions.previous.4", "{\"s\":1368746549002,\"a\":25,\"t\":497,\"c\":true,\"m\":16,\"fp\":1184,\"sr\":1209}");
user_pref("datareporting.sessions.previous.5", "{\"s\":1368747059270,\"a\":5,\"t\":27,\"c\":true,\"m\":17,\"fp\":1064,\"sr\":1087}");
user_pref("datareporting.sessions.previous.6", "{\"s\":1368747139614,\"a\":4,\"t\":28,\"c\":true,\"m\":14,\"fp\":1046,\"sr\":1071}");
user_pref("datareporting.sessions.previous.7", "{\"s\":1368747169529,\"a\":5,\"t\":47,\"c\":true,\"m\":16,\"fp\":1088,\"sr\":1115}");
user_pref("datareporting.sessions.previous.8", "{\"s\":1368747218251,\"a\":5,\"t\":26,\"c\":true,\"m\":17,\"fp\":1070,\"sr\":1096}");
user_pref("datareporting.sessions.previous.9", "{\"s\":1368747389642,\"a\":2,\"t\":34,\"c\":true,\"m\":12,\"fp\":1074,\"sr\":1095}");
user_pref("dom.mozApps.used", true);
user_pref("dom.w3c_touch_events.expose", false);
user_pref("extensions.adblockedge.currentVersion", "2.0.3");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.bootstrappedAddons", "{\"{fe272bd1-5f76-4ea4-8501-a05d35d823fc}\":{\"version\":\"2.0.3\",\"type\":\"extension\",\"descriptor\":\"/home/user/.mozilla/firefox/sk25m38t.default/extensions/{fe272bd1-5f76-4ea4-8501-a05d35d823fc}.xpi\"}}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:21.0");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/home/user/.firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1368306682000,\"rdfTime\":1368306200000}}},{\"name\":\"app-profile\",\"addons\":{\"{fe272bd1-5f76-4ea4-8501-a05d35d823fc}\":{\"descriptor\":\"/home/user/.mozilla/firefox/sk25m38t.default/extensions/{fe272bd1-5f76-4ea4-8501-a05d35d823fc}.xpi\",\"mtime\":1368745485000}}}]");
user_pref("extensions.lastAppVersion", "21.0");
user_pref("extensions.lastPlatformVersion", "21.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://search/adblock");
user_pref("extensions.ui.locale.hidden", true);
user_pref("gecko.buildID", "20130511120803");
user_pref("gecko.mstone", "21.0");
user_pref("intl.charsetmenu.browser.cache", "windows-1252, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 1);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("pref.downloads.disable_button.edit_actions", false);
user_pref("privacy.cpd.offlineApps", true);
user_pref("privacy.cpd.siteSettings", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("privacy.sanitize.timeSpan", 0);
user_pref("toolkit.startup.last_success", 1368748494);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1371336167);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
user_pref("xpinstall.whitelist.add.36", "");
