#!/bin/bash

ToKillPid=$(pgrep -f "yad --no-buttons --skip-taskbar --icons --undecorated --on-top --read-dir=/usr/share/actions/Search --width=565 --height=270")

kill $ToKillPid


SearchTerms=$(yad --entry --width="250" --title="Search Amazon" --window-icon="/usr/share/actions/Icons/Amazon.png")

ret="$?"

if [ "$ret" = "252" ]; then
 exit 0
elif [ "$ret" = "1" ]; then
 exit 0
fi


cp -f /usr/share/actions/Scripts/amazonsearch.html /tmp

sed -i -e "s|Microsoft|$SearchTerms|g" /tmp/amazonsearch.html

exo-open --launch WebBrowser /tmp/amazonsearch.html &

exit