#!/bin/bash
ToKillPid=$(pgrep -f "yad --no-buttons --skip-taskbar --icons --undecorated --on-top --read-dir=/usr/share/actions/Places --width=380 --height=250")

kill $ToKillPid

exo-open --launch FileManager $HOME/Downloads

exit